### ISSUE TITLE
Code does not seeem to include all the set up scripts

### ISSUE THREAD

**Issue by fgregg** [dchud/osha-dedupe#1]
Hi, I'm the author of dedupe and Benjamin told me you were having some trouble getting it work for you.

Could you provide some more documentation on how to get everything setup.

I got to this point:

``` python
> python pgdedupe.py 
Traceback (most recent call last):
  File "pgdedupe.py", line 288, in <module>
    main(args)
  File "pgdedupe.py", line 88, in main
    c.execute('SELECT COUNT(*) AS count FROM %s' % SOURCE_TABLE)
  File "/home/fgregg/public/osha-dedupe/.env/lib/python3.4/site-packages/psycopg2/extras.py", line 223, in execute
    return super(RealDictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: relation "records" does not exist
LINE 1: SELECT COUNT(*) AS count FROM records
```

**Comment by bbengfort** [comment]
@fgregg we were literally just talking about this when we noticed your comment!

**Comment by dchud** [comment]
Thanks for taking a look @fgregg - we'll have more setup details in the README soon.

**Comment by dchud** [comment]
Hi again @fgregg - many more details are now in the README.  As this is more of a learning project than a standalone library or project, I haven't pushed much further on the code itself beyond trying to get it to complete successfully on this dataset.  When it's working, we'll reevaluate and decide what to do next.  As of right now, I've had the job running for a little over two days, and am hoping for a successful result.
